DISCORD_CLIENT_ID: "your_discord_client_id"
DISCORD_CLIENT_SECRET: "your_discord_client_secret"
DISCORD_CALLBACK_URL: "your_discord_callback_url"
DISCORD_GUILD_ID: "your_guild_id"
DISCORD_ROOT_ID: "role_id_for_root,role_id_for_another_role"
DISCORD_BOT_TOKEN: "your_bot_token"
MONGO_URI: "mongodb+srv://username:password@cluster0.mongodb.net/myDatabase?retryWrites=true&w=majority"

