name: Fetch Discord Users

on:
  schedule:
    - cron: '*/1 * * * *'  # Uruchamia co minutę

jobs:
  fetch-users:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script to fetch Discord users
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: node api/fetchDiscordUsers.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ceo_users.json query_users.json
          git commit -m "Update Discord users data [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
