services:
  - type: web
    name: pgt-esports-website
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: DISCORD_CLIENT_ID
        value: YOUR_DISCORD_CLIENT_ID
      - key: DISCORD_CLIENT_SECRET
        value: YOUR_DISCORD_CLIENT_SECRET
      - key: DISCORD_CALLBACK_URL
        value: YOUR_DISCORD_CALLBACK_URL
      - key: DISCORD_GUILD_ID
        value: YOUR_DISCORD_GUILD_ID
      - key: PORT
        value: 3000
